image: python:3.11

stages:
  - pre-commit

cache:
  key:
    files:
      - .pre-commit-config.yaml
  paths:
    - .cache/pre-commit

variables:
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

pre-commit:
  stage: pre-commit
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files --hook-stage pre-push --show-diff-on-failure
    - pre-commit run --all-files --show-diff-on-failure
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "next"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
